<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>BoringWindowsHelper</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Boring.Core/Boring.Core.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="PDFsharp" Version="6.2.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.4" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../boringNotch/Resources/Romanization/*" Link="Romanization/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
